### ISSUE TITLE
Memory issue due to github.com/openconfig/goyang/pkg/yang#typeDictionary

### ISSUE THREAD

**Issue by ivajloip** [openconfig/goyang#103]
Hello,

I am using your great library while working on an implementation of a library that is parsing yang files and does some processing with them (in relation to [this][1]). Recently I realized parsing many models makes my library leak memory. After some debugging I discovered that it should be because of the use of [typeDict][2] that is growing with each model parsing. I would be willing to work on resolving this issue, but as I saw that there is already a `TODO` comment around it, I imagine you already have an idea what would be a good solution for you. The best solution for me would be to have reference to the `typeDict` in the `Modules` type, but it seems that some initialization is done for the _default_ types, which would make that more difficult (we can have separate `typeDict` for the built-in types and the parsed ones). Do you have better ideas and would you be willing to review and possibly merge such a change?

Thank you in advance!

[1]: https://datatracker.ietf.org/doc/draft-petrov-t2trg-youpi/
[2]: https://github.com/openconfig/goyang/blob/master/pkg/yang/types.go#L41

**Comment by robshakir** [comment]
Hi Ivaylo,

The `TODO` here was Paul's initial thoughts about how this might change, but I don't think it's been a problem for us, such that we haven't placed much priority on amending this TODO.  Our applications, today, usually parse the YANG modules and then output some other code that we use elsewhere (e.g., [ygot](https://github.com/openconfig/ygot). I can see that if you're doing a lot of module processing, then this would grow without bounds (since it's not cleaned up).

I'm open to a change whereby we make this part of the `Modules` type - such that within a particular context then this would be cleaned up when that parsing is discarded. I'm open to reviewing changes for this -- please feel free to open a PR.

Cheers,
r.

**Comment by ivajloip** [comment]
Hi Rob,

Thank you for the quick reply and the expressed willingness to review a possible change. The proposed fix is now published. If you need clarifications or other changes, please don't hesitate to let me know. One Possible modification that I was considering, but decided to wait for your input before implementing it, is to try to add some tests related to the fixed issue. My concern about this is that the test that I could think of, which is quite similar to what I did to test the proposed change locally, is to run a good number of parsings and observe if the application has allocated more than some amount of memory. In order for the tests to be more reliable, the number of parsings need to be high enough, which might take at least few seconds, possibly more depending on the hardware running the tests. I am not sure if such test/s would be something you would want to have.

Another possible change that I thought about is having a version of `BuildAST` that takes `Modules` reference. Currently `BuildAST` is part of your public API and I don't expect you to want to change it, but providing an alternative that is safer in terms of memory usage might be something you would want to have.

Thanks,
Ivo

**Comment by andaru** [comment]
Hi Ivo, thanks for raising the issue and posting a fix.

Personally, I think the refactoring you've presented is good; we could later refactor the `Modules` type to include a type dictionary and refactor the calls you've changed in your PR to refer to a `typeDict` contained within a `Modules` reference.

Further, I agree with the suggestion about refactoring the public API to include a `*Modules` argument (or similar), again supported by your PR here.

Apologies for the delay getting this reviewed; I'll proceed with a review today pending others' input on this issue.

Do others have any further comments on Ivo's input, extracting `*Modules` or related factoring issues?

**Comment by nadddy** [comment]
Please review and merge the pull request if the solution is acceptable. I am facing memory leak because of typeDict when loading module and then removing it.

**Comment by wenovus** [comment]
v0.2.7 contains the fix.
