### ISSUE TITLE
'extensions' are not copied into 'uses''s 'grouping'

### ISSUE THREAD

**Issue by LeonGWang** [openconfig/goyang#106]
`extension` keyword is not currently implemented, but `extension` statements found in YANG files are stored in `*yang.Entry.Exts` field. `ygot` can retrieve `extension` statements from this field and perform further processing.

However, because `uses`'s `grouping` are returned as a deep-copy in `ToEntry()` (https://github.com/openconfig/goyang/blob/master/pkg/yang/entry.go#L584), and that the deep-copying function does not copy the `Exts` field (https://github.com/openconfig/goyang/blob/master/pkg/yang/entry.go#L1278), `extension` statements defined within a `uses`'s `grouping` are effectively lost. This impacts downstream `ygot` and `protogen` usage.

The comment at https://github.com/openconfig/goyang/blob/master/pkg/yang/entry.go#L1281 said there wasn't a clear use case of copying the `Ext` field, but I believe we do now.

What's your opinion on this matter?

**Comment by wenovus** [comment]
I'm not familiar with all parts of the code, so bear with me if I need to look into something.

Looking at this one, it looks like `Ext` is still shallow-copied, just not deep-copied. There is a reason to need a deep copy for `Entry`'s `Dir` field due to leafrefs being possibly different for multiple grouping usages. Is there a reason you found to need the `Ext` field to be deep-copied?

**Comment by LeonGWang** [comment]
Sorry for not making my case clearer in the original post.

`Ext` field needs to be deep-copied because `*Grouping*` itself is not permitted to have `extension` substatements according to the RFCs (RFC6020: https://tools.ietf.org/html/rfc6020#section-7.11.1 and RFC7950 https://tools.ietf.org/html/rfc7950#section-7.12.1). Therefore, the relevant `extension` substatements under a Grouping `Entry` all belong to the `Entry`s in the Grouping `Entry.Dir` field.

**Comment by wenovus** [comment]
So I think despite its name suggestion that it contains an `extension` statement, it's actually a usage statement (and not the definition statement): https://tools.ietf.org/html/rfc7950#section-7.19.3

See
https://github.com/openconfig/goyang/blob/master/pkg/yang/ast.go#L160
https://github.com/openconfig/goyang/blob/master/pkg/yang/ast.go#L310

The definition statement is handled differently by this function:
https://github.com/openconfig/goyang/blob/master/pkg/yang/ast.go#L422
and stored in this field https://github.com/openconfig/goyang/blob/master/pkg/yang/yang.go#L117

**Comment by LeonGWang** [comment]
Sorry for the confusion. I didn't think about the distinction between a definition statement and an usage statement.

What I meant to say are `extension` usage statements defined in `Entries` under a grouping `Entry` are lost because they are not deep-copied.

I didn't realize the grouping `Entry` itself may also have `extension` usage statements and these are shallow-copied. However, that doesn't address my usage concerns.

**Comment by wenovus** [comment]
Could you be a little more specific about your issue? I still don't understand why shallow copy is a problem. Could you not refer to the statements using the pointer?

**Comment by LeonGWang** [comment]
For example, if we have the following YANG module:

`
module example {
    yang-version "1";

    prefix "ex";
    namespace "https://example";

    import extensions { prefix exts; }

    container C {
        exts:extension 1;
        uses G;
    }

    grouping G {
        exts:extension 2;
        
        leaf L {
            type int;
            exts:extension 3;
        }    
    }
`

My understanding is `exts:extension 1` and `exts:extension 2` will be copied from `Node` to `Entry` during `ToEntry()`. However, `exts:extension 3` will not be found in leaf `L`'s `Entry`, because it wasn't copied during the deep-copy of of leaf `L`'s `Entry`.

**Comment by wenovus** [comment]
You mean rather that grouping G's direct `exts:extension2` will not be copied. That's correct, the actual place that should be handling this is at the `merge` function. let me check if that's something we'd like to fix.

**Comment by LeonGWang** [comment]
Wouldn't grouping G's direct `exts:extension 2` be copied to the deep-copied grouping `Entry` in the defer function in `ToEntry()`? (https://github.com/openconfig/goyang/blob/master/pkg/yang/entry.go#L505)

However, grouping `Entry`'s child `Entries`, their extension usage statements (i.e. `exts:extension 3`) will not be deep-copied from the original, and the above defer function doesn't affect them. Therefore their extension usage statements won't be able to be found.

This is my understanding of the problem. Please let me know if I overlooked anything.

**Comment by wenovus** [comment]
See this test snippet which demonstrates that extensions2 is not there and extension3 is:
[tmp.txt](https://github.com/openconfig/goyang/files/3962994/tmp.txt)

After the dup, `merge` is the final step to attach the orphan group to its parent, and it's there where it's lost.
https://github.com/openconfig/goyang/blob/master/pkg/yang/entry.go#L1319

**Comment by LeonGWang** [comment]
Hey wenovus, thanks for the diff file!

I see what you mean now. The discussion in this issue is mostly off-topic because of my lack of understanding of how `extensions` are copied when building the `Entry` tree. 

I will close this issue and open a new one to focus on the actual problem you've illustrated.
