### ISSUE TITLE
'Entry.Ext' field is lost during 'merge()'

### ISSUE THREAD

**Issue by LeonGWang** [openconfig/goyang#108]
@wenovus This is a correction to the misguided issue #106 

Given an example module like so, 
```
module example {
    yang-version "1";

    prefix "ex";
    namespace "https://example";

    import extensions { prefix exts; }

    container C {
        exts:extension 1;
        uses G {
            exts:extension 2;
        }
    }

    grouping G {
        exts:extension 3;
        
        leaf L {
            exts:extension 4;
            type int;
        } 

        container C2 {
            leaf L2 {
                type int;
            }
        }
    }
}
```
I would expect `ext:extension2` and `ext:extension3` are kept in the `Entry.Ext` field of all direct child `Entry` of `grouping G`. In another word, the above module should result in the same `Entry` tree as this module:
```
module example {
    yang-version "1";

    prefix "ex";
    namespace "https://example";

    import extensions { prefix exts; }

    container C {
        exts:extension 1;

        leaf L {
            exts:extension 2;
            exts:extension 3;
            exts:extension 4;
            type int;
        }

        container C2 {
            exts:extension 2;
            exts:extension 3;
            leaf L2 {
                type int;
            }
        }
    }
}
```
However, because `Entry.Ext` field of the merged `Entry` is not kept during `merge()`, `exts:extension 2` and `ext:extension 3` are lost. The `Entry` tree we get from our first example module is currently equivalent to this last module:
```
module example {
    yang-version "1";

    prefix "ex";
    namespace "https://example";

    import extensions { prefix exts; }

    container C {
        exts:extension 1;

        leaf L {
            exts:extension 4;
            type int;
        }

        container C2 {
            leaf L2 {
                type int;
            }
        }
    }
}
```

**Comment by wenovus** [comment]
From https://tools.ietf.org/html/rfc7950#section-7.12
```
... Prefix mappings, type names, grouping names, and extension usage are evaluated in the hierarchy where the "grouping" statement appears.  For extensions, this means that extensions defined as direct children to a "grouping" statement are applied to the grouping itself.
```
It's not entirely clear to me what "the grouping itself" means, but it does sound closer to your proposal where the extension is omitted from the node containing the use statement. Anees also has the same opinion on what this intuitively should mean. It would be good to hear your thoughts on this as well, but it seems like this proposal is accepted.

**Comment by LeonGWang** [comment]
I agree with your and Anees's interpretation. This is what I had in mind, though I had not looked up the relevant sections in the RFC to verify and support my intuition. Thanks for the verification!

If the proposal is accepted, when can I expect this to be implemented?
