### ISSUE TITLE
What's the tree format in this project?

### ISSUE THREAD

**Issue by fredgan** [openconfig/goyang#111]
Hi~

I know the tree format in [RFC8340](https://tools.ietf.org/html/rfc8340)

But I find that the tree format in this project:

```
tree - a simple tree representation
```

It's not the same as the RFC. Any specification about this?

**Comment by wenovus** [comment]
Sorry for the delayed response. As far as I understand, goyang's CLI display tool wasn't written at the time to adhere strictly to some specification -- there isn't even a test for it. Furthermore, tree.go was written quite a bit before this RFC, so perhaps there was no clear need yet for a standardized output format.

**Comment by fredgan** [comment]
Well, OK
