### ISSUE TITLE
range statement verification handles `min` and `max` incorrectly

### ISSUE THREAD

**Issue by wenovus** [openconfig/goyang#128]
`goyang` currently has a bug whereby it always recognizes `min` and `max` as the min and max of the root type (i.e. uint64, int8, etc.) instead of its [direct typedef parent](https://tools.ietf.org/html/rfc7950#section-9.2.5). This leads to an incorrect (overly-lenient) verification of YANG types during AST construction ([example file](https://github.com/openconfig/goyang/files/4828305/test.yang.txt)), and to an incorrect (overly-lenient) validation of actual values for downstream libraries such as `ygot` when `min` or `max` are not -inf and +inf.

To fix this, each `Number` simply needs to know the actual values of `min` and `max`, and the easiest way to do that would be to abolish `MinNumber`/`MaxNumber` ([link](https://github.com/openconfig/goyang/blob/master/pkg/yang/types_builtin.go#L503)), and use the actual values instead.

This is a backwards-incompatible change, but just like #125, I believe the usability improvement is worth the cost, as it also fixes bugs.

The proposed changes have the following backwards-incompatible components:
- `MaxNumber`/`MinNumber` will be removed as `Number` types. All numbers will be concrete values once parsed into a `Number` type.

- `ParseInt`, `ParseDecimal`, `ParseRangesInt`, and `ParseRangesDecimal` will now take min/max as function parameters to resolve `min` and `max` inputs to concrete values when parsing.

It fixes the following:
- `YangRange.Contains` will filter out invalid YANG that currently would pass.
- `YangRange` will store only concrete values, making range validations much easier for downstream libraries such as `ygot`.

**Comment by robshakir** [comment]
We discussed this in real-time some time ago, and agreed that this looked like a reasonable change to make - particularly because it seemed to constrain the complexities of understanding this type inheritance within the `pkg/yang` library. 

@wenovus -- did we get a PR together to change this, or is it a backlog item?

**Comment by wenovus** [comment]
@robshakir It's a backlog item. I'm looking to finish it when #125 is merged as it's dependent on it.
