### ISSUE TITLE
goyang installation is failing

### ISSUE THREAD

**Issue by nileshsimaria** [openconfig/goyang#13]
goyang installation is failing as shown below.

[user@host ~/go/src ] go get github.com/openconfig/goyang
package github.com/openconfig/goyang
	imports runtime/trace: unrecognized import path "runtime/trace"

[user@host ~/go/src ] go version
go version go1.4.2 darwin/amd64

System Version:	OS X 10.10.5 (14F1509)
Kernel Version:	Darwin 14.5.0

Thanks,
Nilesh

**Comment by pborman** [comment]
The runtime/trace package is part of the standard go 1.5 release.  It is referenced in github.com/openconfig/goyang/yang.go.  It can be safely removed by commenting out/deleting the getopt line for "trace" and the code block identified by "if traceP != "" {"

**Comment by nileshsimaria** [comment]
Thanks. I also moved to go1.5 and installation of goyang is happening without any issue.

Thanks,
Nilesh
