### ISSUE TITLE
union []*YangType doesn't contain all enumeration subtypes

### ISSUE THREAD

**Issue by wenovus** [openconfig/goyang#131]
There is some incorrect behaviour where if there are multiple enumerations (typedef or not) within a union, then goyang fails to put all of them within the []*YangType field, meaning downstream tools will not recognize them.

There is some further strange behaviour where if these ignored enumerations are put within another level of nested union, some of them are then added to the AST. In any case, more testing and corresponding fixes are needed for this.

**Comment by robshakir** [comment]
@wenovus Was this still pending?

**Comment by wenovus** [comment]
This this is still pending to be addressed.
