### ISSUE TITLE
releases builds and semantic versioning

### ISSUE THREAD

**Issue by hellt** [openconfig/goyang#134]
Hi team,
thank you all for making `goyang` a reality.

I would like to know if the maintainers are up to adopt the semantic versioning for `goyang`? I think the common benefits of a versioned package are well-known.
Aside from the common versioning benefits the adoption will also make it possible to create an automatic release pipeline powered by [goreleaser](https://goreleaser.com/) and github actions (like we did for [gnmic](https://github.com/karimra/gnmic/blob/master/.github/workflows/release.yml)).

Having pre-built `goyang` binaries ready available and downloadable (via github releases) will help users to leverage one of the best yang compilers out there. I am willing to contribute the release pipeline if the OC community is up for maintaining the versioning.

**Comment by robshakir** [comment]
Hi Roman,

We've discussed versioning - so I'd certainly be fine with adding a semver flag here. We've discussed that there are some backwards-incompatible changes to the public API of `pkg/yang` that we'd like to make to support Y1.1 changes of cardinality, and this would help with this.

One question that I have is the benefit of creating binaries -- the `goyang` binary that is in the root of this directory is generally an example of using `pkg/yang`. It does some "potentially useful" things, but I'm not clear that it has been a tool that has had wide applicability. Do you see benefits of releasing this binary - vs. simply having tagged releases that allow for tooling that relies on `pkg/...` to have a stable version?

Thanks,
r.

**Comment by hellt** [comment]
Hi @robshakir,
You're right, I was confused by the `goyang` CLI example that is used to generate a tree view of a model.
If there is no intention to make `goyang` to be a CLI tool with various output formatters - then building a binary is not as useful as it was intended to be.

I am ok with closing this issue if `goyang tree` is just an example and no additional outputs (like in `pyang`) are expected to come

**Comment by robshakir** [comment]
We're open to making it do more if there's demand to do so :-)

In the current pipelines that we're building (in OpenConfig), we generally don't build on-top of the `goyang` binary - we're generally trying to avoid there being a single monolithic blob, and rather have the different components of the toolchains around YANG being separable, with clear API boundaries. In our end-state (with some refactoring supporting this implementation), we are aiming for:

 * `goyang/pkg/yang` being the means to parse YANG files, do lexical, syntatic and semantic (according to the YANG specification) analysis, and output a set of `yang.Entry` types which can be parsed by a downstream consumer.
 * `ygot/ygen` as a means to create an intermediate representation specifically for code generation.
 * Various downstream packages then generating code from this intermediate representation.

Our focus has generally been using this toolchain to be able to generate code, but there are some consumers that will directly use the `goyang/pkg/yang` output (e.g., the `goyang` binary today) to add output formats here -- so maybe we will see that set expanded going forward.

One difference between `goyang` and `pyang` is the need to build a binary - for `pyang`, it's fine to use the plugin directory and just have the python interpreter handle new formats, `goyang` would need to have a reasonable means to register new formats, and they would need to be checked in here (or added as an external dependency), it's not quite clear to me that there's a big benefit here in doing this (rather, it might be best to have folks that have these new output formats build their own binaries). WDYT?

I do want to pursue the approach of semantically versioning `goyang` though, so we should leave this issue open.

Cheers,
r.

**Comment by hellt** [comment]
Thanks for the expanded reply, from this I gather its better to proceed with creating a downstream package/tool that will leverage `goyang/pkg` to generate various outputs/do_some_other_nice_stuff.
Thats what I wanted to know - the strategy for supporting output formats in-or-out of `goyang` repo.

I gather there is indeed a demand for a fast YANG formatter as the models grow larger and richer. `pyang` takes quite some time to generate trees or jstrees from the combined models, and although exec time is not of a grave importance most of the time, it is still nice to see a job done in 3s vs 1m.

So I will proceed with building a standalone CLI tool that will dump the XPATH/RESTCONF paths for a given module using `goyang` as the compiler:
```
❯ go run . path -y ~/projects/openconfig/public/third_party -y ~/projects/openconfig/public/release/models/types -y ~/projects/openconfig/public/release/models/openconfig-extensions.yang -y ~/projects/openconfig/public/release/models/interfaces -m openconfig-interfaces

openconfig-interfaces    /interfaces/interface[name=*]/config/description    string
openconfig-interfaces    /interfaces/interface[name=*]/config/enabled    boolean
openconfig-interfaces    /interfaces/interface[name=*]/config/loopback-mode    boolean
openconfig-interfaces    /interfaces/interface[name=*]/config/mtu    uint16
openconfig-interfaces    /interfaces/interface[name=*]/config/name    string
openconfig-interfaces    /interfaces/interface[name=*]/config/type    identityref -> ietf-if:interface-type
openconfig-interfaces    /interfaces/interface[name=*]/hold-time/config/down    uint32
openconfig-interfaces    /interfaces/interface[name=*]/hold-time/config/up    uint32
openconfig-interfaces    /interfaces/interface[name=*]/hold-time/state/down    uint32
openconfig-interfaces    /interfaces/interface[name=*]/hold-time/state/up    uint32
<OUTPUT CLIPPED>
```

**Comment by robshakir** [comment]
I agree that it's good to have something high performance here. I wonder whether we could say that there are some "display only" generations that `goyang` can be useful for -- and are commonly useful. For example, there are:

* your path output above, and a similar "paths" output that we maintain in `oc-pyang` [here](https://github.com/openconfig/oc-pyang/blob/master/openconfig_pyang/plugins/yangpath.py).
* a documentation generator which produces the output on [ops.openconfig.net](https://ops.openconfig.net)
* the `goyang` "tree" format (which we maybe should align with RFC8340).

Especially on the first one of these, I see the advantage of having this centralised and easily discoverable -- if you're interested in contributing it, this could be a good start to something we could maintain in `goyang`. We can update the docs to reflect this change in purpose :-)

r.

**Comment by hellt** [comment]
I didn't know about oc-pyang paths plugin before we started doing our own with goyang 😬 but the performance benefit is worth it anyways 

In my opinion having a centrally maintained, promoted and documented display-only outputs leveraging goyang is an OC feature community will greatly appreciate. 

Apart from the path information (xpath and restconf styled) I feel that `tree` and a [modernized](https://gitlab.com/rdodin/pics/-/wikis/uploads/ad013fddf9a02ee430c5b5d3a69670ff/image.png) `jstree` outputs are worth adding. 

To address the immediate need for a fast path extractor I plan to create a standalone CLI tool, but I'm up to propose a PR against the goyang with that additional output format

**Comment by hellt** [comment]
the original question has been answered
