### ISSUE TITLE
Why ms.add() adds two modules if the module file comes with a revision

### ISSUE THREAD

**Issue by hellt** [openconfig/goyang#137]
Hi *,
If I have a YANG module which comes in a form `name@revision.yang` and I provide a full path to that file to the `ms.Read()` function:

```go
ms := yang.NewModules()
if err := ms.Read("/tmp/junos-conf-system@2019-01-01.yang"); err != nil {
    log.Info(err)
}
```

I end up having two modules added to the `ms`:
![image](https://user-images.githubusercontent.com/5679861/92006009-7bdf1d00-ed44-11ea-9e1d-ab8e0944f980.png)

This is due to that part which I can't quite understand the meaning of - https://github.com/openconfig/goyang/blob/master/pkg/yang/modules.go#L148

Is this intended? If so, what is the purpose of duplicating the modules under the name with a revision as well as without it?

/cc @andaru @robshakir

**Comment by robshakir** [comment]
This is intended behaviour -- the YANG behaviour being supported here is the ability to import both by revision, and import without the revision (see [this section of rfc6020](https://tools.ietf.org/html/rfc6020#section-5.1.1)). When a module author specifies that there is import _without_ a revision ID, then we need to use the latest version, but we also need to support other versions of that module that might have different revision IDs, thus:

* We add module@revision to the map such that import-by-revision works for this version
* If the module is the newest revision that we've seen, then we make this the version also be the 'bare' module name, such that anyone that isn't importing by revision gets this version.

It's likely that we should probably also do this for modules that don't have the filename `module@version`, and eventually may want to support this for a semantic version - but I'm not aware of widespread use of import by revision today.

r.

**Comment by hellt** [comment]
Thank you for the clarification, @robshakir

**Comment by hellt** [comment]
@robshakir can you please also advise if the logic of resolving module imports is capable of resolving revisioned modules?

I am struggling to make goyang to parse Juniper yang modules, which come as the files with `name@revision.yang` name pattern - https://github.com/Juniper/yang/tree/master/20.2/20.2R1/junos/conf

The following piece is of particular interest to me:

1. If the module imports another module with a specified revision ([example](https://github.com/Juniper/yang/blob/master/20.2/20.2R1/junos/conf/junos-conf-fabric%402019-01-01.yang#L12))
    ```
   import junos-common-types {
     prefix jt;
     revision-date 2019-01-01;
   }
    ```
    the goyang doesn't use the specified revision, when it tries to read the modules on the fly. Instead it uses the "bare" name - https://github.com/openconfig/goyang/blob/master/pkg/yang/modules.go#L188
2. this results in `ms.Read` to operate on `junos-common-types` instead of `junos-common-types@2019-01-01` name.
3. The `ms.Read` in its turn uses `findFile` that [promises](https://github.com/openconfig/goyang/blob/78bac27bdff13f30ab67a3019445f5a59e3f64d5/pkg/yang/file.go#L82-L84) to pick the latest revision found, which is not what the import statement wanted.

Do you see this as an issue? If yes, what options do we have to alleviate this problem of importing the revisioned files?

The first things that came to my mind:

a) try and read the module by its bare name (sometimes the bare name is a symlink to a revision file)
b) if a) is not successful, try and read the `name@revision` module
