### ISSUE TITLE
findFile doesn't perform recursive search for regular paths

### ISSUE THREAD

**Issue by hellt** [openconfig/goyang#138]
Hi *,
[`findFile`](https://github.com/openconfig/goyang/blob/78bac27bdff13f30ab67a3019445f5a59e3f64d5/pkg/yang/file.go#L78) func promises to recursively traverse the paths in [`Path`](https://github.com/openconfig/goyang/blob/78bac27bdff13f30ab67a3019445f5a59e3f64d5/pkg/yang/file.go#L30) and find the file by a module name or by `name@revision` pattern.

From what I see, the only traversal search for revisioned files is done for the paths that end with `...`
https://github.com/openconfig/goyang/blob/78bac27bdff13f30ab67a3019445f5a59e3f64d5/pkg/yang/file.go#L110-L123

When the path is a regular realpath, then scanDir is not called, and a the path is concatenated with module name (L115).

Should it be fixed to be like that?:

```go
	for _, dir := range Path {
		var n string
		if filepath.Base(dir) == "..." {
			n = scanDir(filepath.Dir(dir), name, true)
		} else {
			n = scanDir(dir, name, true)
		}
```

In that case even if the paths is `/a/b/c` the search will be done and the latest revision will be picked up

**Comment by wenovus** [comment]
Do you mean `n = scanDir(dir, name, false)` to pick up the latest revision, but avoid the recursion when the path doesn't end with "..."?

**Comment by hellt** [comment]
@wenovus 
Yes, it can be used for paths which refer to a directory which has imported revisioned modules without nested directories.

But tbh I didn't even know that I can specify a path with /... in the end to make scanDir to kick in until I read the source code.

**Comment by wenovus** [comment]
Ok, yeah it definitely looks like it should use scanDir, and some comments should be added for `AddPath` and `Path`.
