### ISSUE TITLE
issues with resolving import-by-revision statements

### ISSUE THREAD

**Issue by hellt** [openconfig/goyang#141]
Hi @robshakir @wenovus,

I am struggling to make goyang parse the modules which have import statements with a specified revision.

To keep things real, lets take an example of Juniper yang modules, which come in the form of YANG files with `name@revision.yang` pattern - https://github.com/Juniper/yang/tree/master/20.2/20.2R1/junos/conf

1. If the module imports another module with a specified revision ([example](https://github.com/Juniper/yang/blob/master/20.2/20.2R1/junos/conf/junos-conf-fabric%402019-01-01.yang#L10-L13))
    ```
   import junos-common-types {
     prefix jt;
     revision-date 2019-01-01;
   }
    ```
    the goyang doesn't seem to use the specified revision when it tries processes the imports. Instead it [uses the "bare" name](https://github.com/openconfig/goyang/blob/master/pkg/yang/modules.go#L187-L190). In the linked code snippet `name` is the bare module name, without revision suffix.
2. this results in `ms.Read` to operate on `junos-common-types` instead of `junos-common-types@2019-01-01` name.
3. The `ms.Read` in its turn uses `findFile` that [promises](https://github.com/openconfig/goyang/blob/78bac27bdff13f30ab67a3019445f5a59e3f64d5/pkg/yang/file.go#L82-L84) to pick the latest revision found, which is not what the import statement wanted.

Shoudn't we instead read the module by revision by doing:

```go
	// Try to read it in.
	if err := ms.Read(rev); err != nil {
		return nil
	}
```

**Comment by wenovus** [comment]
I didn't test it, but maybe #138 fixes this because `ms.Read(name)` now uses `scanDir`?

**Comment by hellt** [comment]
Not entirely I think, because if the revision used in the import will not be the latest one, then `scanDir` will pick the wrong one (latest, instead of a specific one)

**Comment by wenovus** [comment]
Ah I see. If we change to read by the revision, it looks like `Read` will ignore any "bare-name" files, which could contain the specified revision:
https://github.com/openconfig/goyang/blob/6feec38865444b320d6a0704594b3b4dfb7cee1c/pkg/yang/file.go#L142-L151
One way to deal with this is to call `Read` twice, with and without the revision name, so that we can pick up the file in both cases.

**Comment by hellt** [comment]
@wenovus 

Since `rev`'s initial value is the bare module name, can't this be solved by using `ms.Read(rev)`?
If there is no revision in the include/import statement, then `rev == name` and if its specified, then `rev == name@revision`

**Comment by wenovus** [comment]
When the line you referenced is reached, rev has already been appended with the revision name if it exists:
https://github.com/openconfig/goyang/blob/6feec38865444b320d6a0704594b3b4dfb7cee1c/pkg/yang/modules.go#L187-L190

If no revision is specified, I agree it doesn't make a difference by using `ms.Read(rev)`.

If a revision is specified, however, my concern is `ms.Read(rev)` would not pick up the bare-name version of the file. According to the [RFC](https://tools.ietf.org/html/rfc7950#section-5.2), the recommended name is `module-or-submodule-name ['@' revision-date] ( '.yang' / '.yin' )`, meaning if, as an edge-case, the repository uses the bare-name to name files, then the file won't be picked up at all when a `revision-date` is specified in an import statement, when in fact it could be the revision that the importing file was looking for.

**Comment by hellt** [comment]
Maybe that approach in #142 can be polished to satisfy the requirements?

**Comment by hellt** [comment]
closing as #142 has been merged, thanks @wenovus
