### ISSUE TITLE
support for yang 1.1 `modifier` pattern substatement

### ISSUE THREAD

**Issue by hellt** [openconfig/goyang#218]
Hi all,
this issues is a feature request to add support for `modifier` pattern substatement as per https://datatracker.ietf.org/doc/html/rfc7950#section-9.4.6

**Comment by vasu-dasari** [comment]
@davidmat50 I have tested the your commit. And it seems to work. Do you have any plans for raising a PR?

**Comment by hellt** [comment]
delivered in https://github.com/openconfig/goyang/pull/241
