### ISSUE TITLE
JSON Representation of `ToInt` and `ToString`

### ISSUE THREAD

**Issue by wenovus** [openconfig/goyang#233]
Hi @robshakir, you mentioned in https://github.com/openconfig/goyang/pull/229#issuecomment-1168672387 that you wanted to agree on whether the JSON representation we have for these two fields are right. I added a comment
https://github.com/openconfig/goyang/pull/229#pullrequestreview-1031987720 where I think it is fine as is. Specifically, the enum names and numbers are both represented exactly as they are declared in the YANG, so I think the representation is appropriate. This is the most direct way of doing the mapping between these two values.

Let me know what you think. Thanks.

**Comment by robshakir** [comment]
Sorry, I agree that these are the right thing to include - but I was wondering about adding test coverage to make sure we don't change them going forward. Thus far, I'm not entirely sure that we've treated the JSON representation of `Entry` as something that should be stable.

Did you find somewhere we already have coverage?

**Comment by wenovus** [comment]
There is existing unit test on the `EnumType` generation https://github.com/openconfig/goyang/pull/229/files#diff-dcce2033ff9325412501138ee4023ee1a5e25781fa0110e82cf6a73242d0519b, and Sean added a JSON marshalling unit test for `EnumType` https://github.com/openconfig/goyang/pull/229/files#diff-8b11730c306c125af5b460be997a2585d0bf568f8bfe616f57ebb17dfdae8283

**Comment by robshakir** [comment]
OK, great! We can close this out :-)
