### ISSUE TITLE
"range" support for decimal values

### ISSUE THREAD

**Issue by andaru** [openconfig/goyang#24]
The `yang.ParseRanges` function uses the `Number` type under the surface, but the `Number` type does not support floating point (decimal) values.

Both YANG 1.0 and the recently ratified YANG 1.1 support `range` restrictions on the `decimal64` type.

I would expect the test below to successfully import the enclosed module, which is successfully validated by pyang 1.7.

``` go
package ttt

import "testing"
import "github.com/openconfig/goyang/pkg/yang"

func TestYANGRangeDecimal64(t *testing.T) {
    mod := `
module test {
  prefix test;
  namespace urn:test;

  leaf d64 {
    type decimal64 {
      fraction-digits 2;
      range "-0.5 .. 1.0";
    }
  }

}
`

    ms := yang.NewModules()
    ms.Parse(mod, "test.yang")
    errs := ms.Process()
    for i, err := range errs {
        t.Errorf("error %d: %v", i, err)
    }
}
```

However the test fails when parsing the `Number` types due to their lack of floating point support:

```
$ go test -v .
=== RUN   TestYANGRangeDecimal64
--- FAIL: TestYANGRangeDecimal64 (0.00s)
    ttt_test.go:26: error 0: test.yang:9:7: bad range: strconv.ParseUint: parsing "0.5": invalid syntax
FAIL
exit status 1
FAIL    github.com/aristanetworks/gopenconfig/ttt   0.008s
```

**Comment by pborman** [comment]
It looks like Number needs to support decimal64 as well and a new kind (Decimal64).  This implies we need to add the precision someplace in the Number as well.  Given the strings "1.0" and "1.00", these would be both stored as 100 but one would have a precision of 1 while the other of 2.  Should these both be considered the same type?  Maybe they should be considered different types.  In that case we can have the types:

Decimal64
Decimal64_1
Decimal64_2
...
Decimal64_18

(The precision is Kind - Decimal64)

If there should only be one kind, Decimal64, then we need a precision field.

I think the Number.add function would still work correctly as when we add "1" we mean the smallest amount we can add, so adding "1" to "1.00" would end up being "1.01" and adding -1 would end up as "0.99".

Thoughts?

**Comment by robshakir** [comment]
My view is that it is OK to consider a `decimal64` with precision 1 the same type as one with precision 2. It's unclear where one would really model something such that they had a different meaning within the model.

If we are generating code from the internal representation, then these cases will all be treated the same in general (mapping to a decimal type, or a float) - and the only case I can see where it is used internally is the scenario where we have:

```yang
leaf foobar {
  type union {
    type decimal64 { fraction-digits 2; }
    type decimal64 { fraction-digits 4; }
  }
}
```

from my read of 6020, then in this case if we took the input of "1.0000" then we should map it to the second member type of the union, rather than the former. However, in practice, I can't see how this is really useful. In the Python code generation, I would actually map it to the first (since we can obviously trivially convert 1.0000 -> 1.00), I think this truncation case will be the common scenario.

If this sounds reasonable, I can take a look at extending `Number`.

**Comment by pborman** [comment]
Is it okay to treat precision 18 the same as precision 1?  I don't think so.

precision 1 and precision 2 support different value ranges (I am throwing in precision 0 (int64) as well):


     | 0              | -9223372036854775808. | 9223372036854775807. |
     | 1              | -922337203685477580.8 | 922337203685477580.7 |
     | 2              | -92233720368547758.08 | 92233720368547758.07 |

Precision 0 is a regular int64 and uses all 64 bits.  Each of these ranges has the identical cardinality, however there are values that are representable in exactly 1 range (9223372036854775807, 922337203685477580.7, 92233720368547758.07) Given there are 18 possible precisions, which is just over 4 bits (lets say 5) then either we constrain the ranges to 27 bits or we need ancillary information.

The string representation would have a canonical form, e.g., 1.0, 1.00, 1.000..., but in terms of parsing, as long as the conversion is lossless, any precision should be allowed (e.g., 1.000 -> prec 1 is fine, but 1.001 -> prec 1 is not fine)

No matter how we slice it, traditional JSON parsing is either going to severely reduce the cardinality of each range or we must externally apply precision (1 could mean 0.1, .001, etc).  We should be careful to always preserve full precision in goyang, but if others decide to cheat and use floating point values for decimal 64, well, it ain't our problem.

**Comment by robshakir** [comment]
@ostromart added support for this in #53 and subsequent PRs. I'll close this issue. Please re-open it if there are things that are still outstanding here (but from my read, I think we're there).
