### ISSUE TITLE
Public function to reset Modules' globals

### ISSUE THREAD

**Issue by eric-rios** [openconfig/goyang#248]
Does it make sense to add a public function that resets the `mergedSubmodule` and `entryCache` variables of a Modules struct? Mainly to have the option of freeing a bit of memory. Could it have any negative impact?

I'm aware it may not be the normal use case, but we have one where we want to be able to completely remove a specific Module (that we know won't impact any other). We noticed that the memory is not being released, likely due to the Module being referenced in one of the previously mentioned variables, and so the garbage collector can't really delete it.

Let me know your thoughts on this, thanks.

**Comment by wenovus** [comment]
Sorry missed this issue. Suggested this PR to cover your use case: https://github.com/openconfig/goyang/pull/260#pullrequestreview-1718558908
