### ISSUE TITLE
when to use yang deviation (not-supported)  and in which scenario status (obsolete) should be used?

### ISSUE THREAD

**Issue by rosy8** [openconfig/goyang#263]

**Comment by wenovus** [comment]
I'd say RFC7950 provides a fairly good description of the distinction:
https://datatracker.ietf.org/doc/html/rfc7950#section-7.20.3
https://datatracker.ietf.org/doc/html/rfc7950#section-7.21.2

This question is better suited to be asked at https://github.com/openconfig/public/issues, feel free to ask any follow-up questions there.
