### ISSUE TITLE
Add handling of circular dependencies

### ISSUE THREAD

**Issue by robshakir** [openconfig/goyang#35]
In some schemas (non-OpenConfig), there exist circular dependencies between a set of submodules, based on YANG 1.0 not considering entities defined in a submodule to be accessible to another submodule of the same module without an explicit `include` statement. Currently, goyang will loop around these statements. This issue tracks adding hooks to handle such cases.

A canonical example case is the one used in (pyangbind unit tests)[https://github.com/robshakir/pyangbind/tree/nokia-fix/tests/nokia]. `mod-a` includes `subm-x` and `subm-b` which include each other.

I plan to add support for a command-line option to be able to handle this case, despite the fact that it violates the requirements of RFC6020. Comments welcome - otherwise I will open a PR.

**Comment by pborman** [comment]
Having it a command line option that sets a public global variable in the yang package seems like a good avenue to take.  Thanks!

**Comment by robshakir** [comment]
Thanks Paul - PR opened.
