### ISSUE TITLE
"default" support for "choice" entries

### ISSUE THREAD

**Issue by LeonGWang** [openconfig/goyang#37]
Currently the `ToEntry` function does not set `default` for type `*Choice`.

I plan on fixing this by adding the same snippet of code that is used in `ToEntry` to set `default` for type `*Leaf`. In the end, it will look as the following:

    ...
    case *Choice:
        e.Kind = ChoiceEntry
        // set `default` for type `*Choice`
        if s.Default != nil {
            e.Default = s.Default.Name
        }
    ...

**Comment by pborman** [comment]
Thanks for the contribution!
