### ISSUE TITLE
prefix handling with grouping/uses is ineffective

### ISSUE THREAD

**Issue by gopenconfig** [openconfig/goyang#7]
For a `yang.Entry`, `Prefix` is only set when the current node has a `prefix` statement. This is only the case for the entry corresponding a `yang.Module`.

When a `grouping` statement is "entry-ised", the entry corresponding the `grouping` has a nil `Parent`. This means that when the `grouping` is placed in a `uses` (i.e., in some other module), we will never be able to ascend the `Parent` entries to determine the current prefix.

One solution would be to simply set the `Prefix` for each entry.

**Comment by andaru** [comment]
A test showing a related set of issues (with a simple 'offending' GetPrefix implementation) can be seen in a related branch in a dev repo I'm working on:

https://github.com/andaru/goyang/tree/andaru/test-getprefix

This commit in particular:

https://github.com/andaru/goyang/commit/2de1f1e92cd8968c1fb7cb9b49a4bc77c510252a

This GetPrefix impl wouldn't be necessary if the Prefix was set for each entry during ToEntry.

**Comment by robshakir** [comment]
@andaru -- I think that you closed this one out too, AFAICS? I also fixed `namespace` on this.

**Comment by andaru** [comment]
Thanks, Rob; after your fixes recently this is all done.
