### ISSUE TITLE
"reference" and "description" inside "import" is not supported

### ISSUE THREAD

**Issue by idryzhov** [openconfig/goyang#76]
YANG 1.1 allows usage of "reference" and "description" statements inside "import" statement.

Example of such usage is in [ietf-routing](https://tools.ietf.org/html/rfc8349#section-7) from [RFC 8349](https://tools.ietf.org/html/rfc8349).

**Comment by LeonGWang** [comment]
@robshakir pull request #92 have addressed this.

**Comment by andaru** [comment]
Closing the issue - confirmed addressed by PR#92.  Thanks for reporting @idryzhov and for the followup, Leon!
